//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Inventory_ID { get; set; }
        public string ISBN { get; set; }
        public int Copies_in_stock { get; set; }
        public string Location { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
