//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sales_ID { get; set; }
        public string ISBN { get; set; }
        public System.DateTime Sales_date { get; set; }
        public int Copies_sold { get; set; }
        public decimal Revenue { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
